export const technologies = [
    'TypeScript',
    'JS ES6+',
    'Node',
    'Express',
    'Redis',
    'PostgreSQL',
    'SQL',
    'MongoDB',
    'RabbitMQ',
    'React',
    'Angular',
    'HTML5',
    'CSS3',
    'SASS',
    'Tailwind',
    'Mongoose',
    'Handlebars',
    'Playwright',
    'Jest',
    'Mocha-Chai',
    'Bootstrap',
    'AntDesign',
    'MUI',
];

export const toolsList = [
    'Docker',
    'Prisma ORM',
    'MySQL',
    'Git',
    'Vite',
    'Prettier',
    'ESLint',
    'Postman',
    'Nodemon',
    'Chrome Dev Tools',
    'React Dev Tools',
    'Angular Dev Tools',
    'Figma',
];

export const skillsList = [
    'Scrapers',
    'REST APIs',
    'Message Queues',
    'Stripe integration',
    'Cloudinary integration',
    'Responsive Design',
    'JsonWebToken',
    'Unit Testing',
    'Integration Testing',
    'E2E Testing',
    'Agile Methodologies',
    'Backendless serverless architecture',
];
